apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust7515744901765394440
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider3flux+cluster3/context/7515744901765394440
  prune: true
  sourceRef:
    kind: GitRepository
    name: "7515744901765394440"
  targetNamespace: default
status: {}
