apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust1004313117630690644
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider3flux+cluster3/context/1004313117630690644
  prune: true
  sourceRef:
    kind: GitRepository
    name: "1004313117630690644"
  targetNamespace: default
status: {}
